activation_mode:
  labels: hjklasdf
app_launch_prefix: ""
as_window: false

builtins:
  ai:
    anthropic:
      prompts:
        - label: General Assistant
          max_tokens: 1000
          model: claude-3-5-sonnet-20241022
          prompt: You are a helpful general assistant. Keep your answers short and precise.
          temperature: 1
    icon: help-browser
    name: ai
    placeholder: AI
    switcher_only: true
    weight: 5
  applications:
    actions:
      enabled: true
      hide_category: false
      hide_without_query: true
    context_aware: true
    hide_actions_with_empty_query: true
    name: applications
    placeholder: Applications
    prioritize_new: true
    refresh: true
    show_generic: true
    show_icon_when_single: true
    show_sub_when_single: true
    weight: 5
  bookmarks:
    entries:
      - keywords:
          - walker
          - github
        label: Walker
        url: https://github.com/abenz1267/walker
    icon: bookmark
    name: bookmarks
    placeholder: Bookmarks
    switcher_only: true
    weight: 5
  calc:
    icon: accessories-calculator
    min_chars: 1
    name: calc
    placeholder: Calculator
    require_number: true
    weight: 5
  clipboard:
    avoid_line_breaks: true
    exec: wl-copy
    image_height: 300
    max_entries: 10
    name: clipboard
    placeholder: Clipboard
    switcher_only: true
    weight: 5
  commands:
    icon: utilities-terminal
    name: commands
    placeholder: Commands
    switcher_only: true
    weight: 5
  custom_commands:
    icon: utilities-terminal
    name: custom_commands
    placeholder: Custom Commands
    weight: 5
    commands:
      - name: search flatpak descriptions
        cmd: ~/scripts/search_flatpak_through_description.sh
      - name: edit image in clipboard
        cmd: bash -c 'wl-paste | satty --filename - --copy-command=wl-copy'
      - name: restart walker service
        cmd: bash -c 'pkill walker; walker --gapplication-service'
      - name: restart xwayland-sattelite
        cmd: bash -c 'pkill -f xwayland-sattelite; niri msg action spawn -- xwayland-sattelite :0'
  dmenu:
    name: dmenu
    placeholder: Dmenu
    switcher_only: true
    weight: 5
  emojis:
    exec: wl-copy
    history: true
    name: emojis
    placeholder: Emojis
    show_unqualified: false
    switcher_only: true
    typeahead: true
    weight: 5
  finder:
    concurrency: 8
    icon: file
    ignore_gitignore: true
    name: finder
    placeholder: Finder
    refresh: true
    show_icon_when_single: true
    switcher_only: true
    use_fd: false
    weight: 5
  runner:
    generic_entry: false
    history: true
    icon: utilities-terminal
    name: runner
    placeholder: Runner
    refresh: true
    typeahead: true
    weight: 1
    switcher_only: false
  ssh:
    history: true
    icon: preferences-system-network
    name: ssh
    placeholder: SSH
    refresh: true
    switcher_only: true
    weight: 5
  switcher:
    name: switcher
    placeholder: Switcher
    prefix: /
    weight: 5
  symbols:
    after_copy: ""
    history: true
    name: symbols
    placeholder: Symbols
    switcher_only: true
    typeahead: true
    weight: 5
  websearch:
    entries:
      - name: Google
        url: https://www.google.com/search?q=%TERM%
      - name: DuckDuckGo
        switcher_only: true
        url: https://duckduckgo.com/?q=%TERM%
      - name: Ecosia
        switcher_only: true
        url: https://www.ecosia.org/search?q=%TERM%
      - name: Yandex
        switcher_only: true
        url: https://yandex.com/search/?text=%TERM%
    icon: applications-internet
    name: websearch
    placeholder: Websearch
    weight: 5
  windows:
    icon: view-restore
    name: windows
    placeholder: Windows
    show_icon_when_single: true
    weight: 5
close_when_open: false
disable_click_to_close: false
events:
  on_activate: ""
  on_exit: ""
  on_launch: ""
  on_query_change: ""
  on_selection: ""
force_keyboard_focus: false
hotreload_theme: false
keys:
  accept_typeahead:
    - alt m
  activation_modifiers:
    alternate: alt
    keep_open: shift
  ai:
    clear_session:
      - ctrl x
    copy_last_response:
      - ctrl c
    resume_session:
      - ctrl r
    run_last_response:
      - ctrl e
  close:
    - esc
  next:
    - tab
    - down
  prev:
    - shift tab
    - up
  remove_from_history:
    - shift backspace
  resume_query:
    - ctrl r
  toggle_exact_search:
    - ctrl m
  trigger_labels: lalt
list:
  dynamic_sub: true
  keyboard_scroll_style: vim
  max_entries: 50
  placeholder: No Results
  show_initial_entries: true
  single_click: true
  visibility_threshold: 20
locale: ""
monitor: ""
search:
  delay: 0
  placeholder: Search...
  resume_last_query: false
terminal_title_flag: ""
theme: default
timeout: 0
